### ISSUE TITLE
Not submitting emails to mail chimp List

### ISSUE THREAD

**Issue by gbrigens** [nzjs/mailchimp-3.0-php-signup#1]
Hi thanks for creating this awesome ready form for mail chimp. I have updated it with my own apikey and listid but its not showing the email on mail chimp after signup. while on the the form it shows successful. What might be the issue here? thanks.

**Comment by nzjs** [comment]
Hi, I would recommend checking the MailChimp API settings for your account, scroll down and view the API request history. Here you should see the request for the email address you've just attempted to add. If it's "Result: checkmark" and says "Response: n/a" it means that it's actually successful and may take up to 10 minutes to update your list. This happened for me a few times.

If the API request says otherwise than stated above, I would check your website's HTML/JS code for the form and make sure that it's similar to the one in the readme - note it should be a form GET request, although the ajax code is set to POST. This is the only way I could get it to work correctly.

**Comment by gbrigens** [comment]
Thanks, I figured it out...I was to close the issue earlier but I got caught up. It was an error on mail chimp side.
